Fix accepts_incomplete issue
In osb-checker in PUT, UPDATE, DELETE API:
should return 422 if request doesn't have the accepts_incomplete parameter:
Error: expected 422 "Unprocessable Entity", got 500 "Internal Server Error"

Related-Bug: theopenlab/openlab#75